### ISSUE TITLE
Allow access to RadioHead packet headers

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_RFM69#11]
I think it would be useful to allow the user to set/read the contents of the RadioHead Packet header:
```
To
From
ID
Flags
```
so multiple radios can distinguish source/recipient

I'm not sure we need the full Reliable Datagram protocol but can start with just providing access to the headers. Now they are discarded on read and set to Broadcast on send. 

Would you like to see this added to the library?  If so, I'll implement it here first then add it to the RF9x as well.

**Comment by ladyada** [comment]
sure :)

**Comment by jerryneedell** [comment]
submitted #12 to implement this.
