### ISSUE TITLE
RSSI values wrong

### ISSUE THREAD

**Issue by marc-gist** [adafruit/Adafruit_CircuitPython_RFM69#22]
I have two radios sitting side by side with antenna.  one runs M0 with C code and returns -23 to -26 when reporting RSSI

the M4 with featherwing reports -87.5 to -90.5.

100 ft away through 4 walls, arduino reports -56, and Python reports same -90.5 as before.

**Comment by jerryneedell** [comment]
Is the -87 --90 with the CircuitPython code? I have been seeing the same thing and keep meaning to dig into it. Not sure what is going on with the RSSI.  Suggestions welcome!

**Comment by marc-gist** [comment]
> Is the -87 --90 with the CircuitPython code? I have been seeing the same thing and keep meaning to dig into it. Not sure what is going on with the RSSI. Suggestions welcome!
> 
> Thanks for opening the issue! Now it won't get forgotten!

yes, its only on the CircuitPython that returns always "large" negative numbers, even when right beside the radio with an antenna attached, or 100m away.  Likely due to an issue in reading/converting the registry value.

**Comment by marc-gist** [comment]
radiohead does this in C:

`return -((int8_t)(spiRead(RH_RF69_REG_24_RSSIVALUE) >> 1));`

where adafruit does a /2.0
Not sure what `>>` does again, I believe shifts bits; but I'm not sure how to translate that to python :(

**Comment by BiffoBear** [comment]
Hi Marc,

Shifting a binary integer right is effectively the same as divide by 2

e.g. 4 in binary is 0b10

0b10 >> 1 is 0b01 = 2

Cheers,

Martin

**Comment by Pythonaire** [comment]
> I have two radios sitting side by side with antenna. one runs M0 with C code and returns -23 to -26 when reporting RSSI
> 
> the M4 with featherwing reports -87.5 to -90.5.
> 
> 100 ft away through 4 walls, arduino reports -56, and Python reports same -90.5 as before.

see definition of RSSI. So high and negative values are correct/good.

**Comment by jerryneedell** [comment]
I think I found the problem.
The RSSI has to be read immediately after the packet is received. It is now being read "on demand" when requested.  When I do this, I get values more like the -26 I see with Arduino rather than the -90 values reported now.
I'll try to get a PR in for this soon along with some other things I've been working on.
Thanks for bring this up -- nice to have it resolved.

**Comment by jerryneedell** [comment]
this change seems to work:
```
diff --git a/adafruit_rfm69.py b/adafruit_rfm69.py
index 2fe8184..17de383 100644
--- a/adafruit_rfm69.py
+++ b/adafruit_rfm69.py
@@ -345,6 +345,8 @@ class RFM69:
         self.encryption_key = encryption_key
         # Set transmit power to 13 dBm, a safe value any module supports.
         self.tx_power = 13
+        # last RSSI reading
+        self.last_rssi = 0.
 
     # pylint: disable=no-member
     # Reconsider this disable when it can be tested.
@@ -765,6 +767,8 @@ class RFM69:
                     timed_out = True
         # Payload ready is set, a packet is in the FIFO.
         packet = None
+        # save RSSI
+        self.last_rssi = self.rssi
         # Enter idle mode to stop receiving other packets.
         self.idle()
         if timed_out:
```
then in your code read rfm69.last_rssi  instead of rfm69.rssi

```
Received (raw header): ['0x1', '0x2', '0xe0', '0x0']
Received (raw payload): bytearray(b'message number 224 from node 2')
Received RSSI: -26.5
```

there may be better ways to do this ...

**Comment by marc-gist** [comment]
thanks @jerryneedell i was wondering that last night when I was looking through docs.  the RH lib also uses "lastRssi()" so this will bring it more into alignment which will make it easier for folks transitioning to CP.

**Comment by Pythonaire** [comment]
> > I have two radios sitting side by side with antenna. one runs M0 with C code and returns -23 to -26 when reporting RSSI
> > the M4 with featherwing reports -87.5 to -90.5.
> > 100 ft away through 4 walls, arduino reports -56, and Python reports same -90.5 as before.
> 
> see definition of RSSI. So high and negative values are correct/good.

sorry, you are right. link quality and rssi are not the same
