### ISSUE TITLE
RuntimeError: Timeout during packet send

### ISSUE THREAD

**Issue by geekguy-wy** [adafruit/Adafruit_CircuitPython_RFM69#26]
I have been working with the RFM69 radio modules and the associated Circuitpython library. There is a **RuntimeError: Timeout during packet send** generated when the send function times out. The library source for this function states that the timeout is only there to prevent hang.

This is fine, but _why_ does there have to be a runtime error generated when this happens?

I propose we _not_ generate an error on this condition.

**Comment by jerryneedell** [comment]
fixed by #27
