### ISSUE TITLE
address a server

### ISSUE THREAD

**Issue by Pythonaire** [adafruit/Adafruit_CircuitPython_RFM69#30]
to prevent useless communication, I used  "rx_filter" to address data packets to a correct destination, the server just listening on packets designated for his own address. Now is see, "rx_filter" was deleted. Why?

**Comment by jerryneedell** [comment]
> to prevent useless communication, I used "rx_filter" to address data packets to a correct destination, the server just listening on packets designated for his own address. Now is see, "rx_filter" was deleted. Why?
Now just set rfm69.node  as an attribute and it will be filtered as it was before. The argument is not needed.   See the rfm69_node1.py example
