### ISSUE TITLE
NetworkID

### ISSUE THREAD

**Issue by smccamy1** [adafruit/Adafruit_CircuitPython_RFM69#32]
Hello, is there a way to set a network id?  My hopes are to be able to use this library on the feather M0 RFM69 to communicate with another nodes I have running the below library:

https://github.com/LowPowerLab/RFM69/blob/master/Examples/Gateway/Gateway.ino

Thanks

**Comment by jerryneedell** [comment]
The CircuitPython RFM69 library is compatible with the RadioHead Arduino Library in terms of the Header used for addressing. I am not familiar with the Low Power Labs format but will take a look at it to see if is or can be compatible. At first glance, it does not look good ...
It may be something that can be added.

**Comment by brentru** [comment]
@smccamy1  What's the purpose of a network ID? How does it differ from a node id (which this library has)?

**Comment by smccamy1** [comment]
@brentru They limit multiple nodes to a single network.  With the libraries that use it, all nodes must be on the same network to communicate.  All of my battery operated nodes run on Moteinos and all the example code uses the lowpowerlabs library.  My hopes are to start using the M0 RFM69 feathers so I can code in python and share the same RFM69 gateway I am already using for my current nodes.  The RadioHead library does state it works on Moteinos.  It may just be less trouble in the long run to setup a separate gateway for circuit python/RadioHead projects.

**Comment by brentru** [comment]
> . It may just be less trouble in the long run to setup a separate gateway for circuit python/RadioHead projects.
I'd suggest doing this for now unless you'd like to add a PR to set a network id.

**Comment by pskowronek** [comment]
I guess it wasn't a good reason to close this valid question.... Please re-open so someone could provide a valid solution.

**Comment by bprobbins** [comment]
rpi-rfm69 may be your answer. https://rpi-rfm69.readthedocs.io/en/latest/index.html
It provides for networkid, encryption, recipientid, and there is an example for using the adafruit rfm69 bonnet.
