### ISSUE TITLE
set_boost oversight?

### ISSUE THREAD

**Issue by tottaka** [adafruit/Adafruit_CircuitPython_RFM69#47]
https://github.com/adafruit/Adafruit_CircuitPython_RFM69/blob/864012e8644f7dc5dfba32a43af52a1f48969c7a/adafruit_rfm69.py#L451

The datasheet for RFM69 says to set two different values for RegTestPa1 and RegTestPa2 when enabling boost, but currently they are set as the same value in the set_boost function which doesn't seem right.

![image](https://github.com/adafruit/Adafruit_CircuitPython_RFM69/assets/55870529/2af866ea-c2f2-4bea-91ed-9f906876b7f5)

**Comment by jerryneedell** [comment]
hmm -- it looks like I introduced this error with PR #44
I'll try to look into fixing it, or you are welcome to submit a PR to fix it if you want.

The changes were made when we were trying to reduce the code size as much as possible and it looks like I got a bit carried away here.

Any changes must be tested on the small build for the feather_m0_rfm69 board to make sure it still fits...

**Comment by jerryneedell** [comment]
Ah -- setting the RegOCP to 0x0F as per the Datasheet does disable the OCP but reviewing the RadioHead library for Arduino, it does not appear that this is implemented there either. RegOCP is always left at the default setting of 0x1A, even for High Power operation.  This does not appear to be correct but I am not sure what impact it has.  I'll raise this question in their forum as well.

**Comment by jerryneedell** [comment]
The documentation in https://cdn-shop.adafruit.com/product-files/3076/sx1231.pdf  is a bit different. See section 3.4.7
There is no mention of disabling the OCP for high power....

**Comment by tottaka** [comment]
> The documentation in https://cdn-shop.adafruit.com/product-files/3076/sx1231.pdf is a bit different. See section 3.4.7 There is no mention of disabling the OCP for high power....

Interesting, maybe I have been looking at the wrong datasheet. I just got mine off the first google result I saw. Please do update me with your changes as I have ported this library to C# and will definitely want to update my code accordingly.

I was considering changing the method (in C#) like so:
`void SetBoost(bool enable_boost)
{
	if(enable_boost)
	{
		WriteRegister(RegisterAddress.PA1, 0x5D);
		WriteRegister(RegisterAddress.PA2, 0x7C);
	}
	else
	{
		WriteRegister(RegisterAddress.PA1, 0x55);
		WriteRegister(RegisterAddress.PA2, 0x70);
	}
}`

**Comment by tottaka** [comment]
> Ah -- setting the RegOCP to 0x0F as per the Datasheet does disable the OCP but reviewing the RadioHead library for Arduino, it does not appear that this is implemented there either. RegOCP is always left at the default setting of 0x1A, even for High Power operation. This does not appear to be correct but I am not sure what impact it has. I'll raise this question in their forum as well.

Reading back, this seems to be an oversight on the RadioHead library as well. There is a note in section 3.3.7 of https://cdn-shop.adafruit.com/product-files/3076/RFM69HCW-V1.1.pdf that states `High Power settings MUST be turned off when using PA0, and in Receive mode.`

**Comment by jerryneedell** [comment]
I have implemented a fix for this and fixed up some other issues regarding the power level reporting. I will do a bit more testing and should have a PR ready this weekend.  IF you want a "sneak peak" you can find the working code here 
https://github.com/jerryneedell/Adafruit_CircuitPython_RFM69/blob/jerryn_power/adafruit_rfm69.py

There was an existing error in the way tx_power was being returned. I think I have fixed that now as well.
I also added code to disable the Overload Current Protection (RegOCP) for tx_power >18 as specified in the Datasheet.

**Comment by jerryneedell** [comment]
@tottaka I would certainly appreciate it if you can test my changes and see if you agree with them.

**Comment by jerryneedell** [comment]
@tottaka I will go ahead and create a PR for this so you can more easily review an comment on it

**Comment by jerryneedell** [comment]
@tottaka please review and comment on https://github.com/adafruit/Adafruit_CircuitPython_RFM69/pull/48

**Comment by jerryneedell** [comment]
@tottaka FYI -- I posted this to the radiohead-ardupino forum https://groups.google.com/g/radiohead-arduino/c/tRn1sibn82o

**Comment by tottaka** [comment]
> @tottaka please review and comment on #48

Looks okay to me, thank you for the quick support!

**Comment by tottaka** [comment]
Actually, why check if high power is enabled in the disable_boost function? If boost needs to be disabled then it should be disabled no matter what, it seems pointless to check if we're in high power mode or not
